# Generated by Django 5.0.2 on 2024-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255)),
                ('drop_address', models.CharField(max_length=255)),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('drop_latitude', models.FloatField(blank=True, null=True)),
                ('drop_longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
