# Generated by Django 4.2.1 on 2024-02-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='drop_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='drop_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
