# Generated by Django 5.0.2 on 2024-03-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='pickup_address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_latitude_1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_latitude_2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_longitude_1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_longitude_2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
