# Generated by Django 5.0.2 on 2024-04-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_ride_pickup_address_1_ride_pickup_address_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(max_length=100, verbose_name='Order ID')),
                ('razorpay_payment_id', models.CharField(max_length=100, verbose_name='Razorpay Payment ID')),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
