# Generated by Django 5.0.2 on 2024-04-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('receipt_id', models.CharField(blank=True, max_length=40, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('partial_payment', models.BooleanField(default=False)),
                ('first_payment_min_amount', models.IntegerField(blank=True, null=True)),
                ('order_status', models.CharField(choices=[('created', 'Created'), ('attempted', 'Attempted'), ('paid', 'Paid')], max_length=20)),
                ('razorpay_payment_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_signature', models.CharField(max_length=120)),
                ('payment_status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('refunded', 'Refunded'), ('failed', 'Failed')], max_length=20)),
                ('payment_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
