# Generated by Django 5.0.2 on 2024-05-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_paypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100, unique=True)),
                ('order_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('order_status', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=255)),
                ('transaction_status', models.CharField(max_length=20)),
            ],
        ),
    ]
