# Generated by Django 5.0.2 on 2024-05-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0002_transaction_paypal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_paypal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
