# Generated by Django 5.0.2 on 2024-05-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0003_alter_transaction_paypal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_paypal',
            name='invoice_id',
            field=models.CharField(max_length=100),
        ),
    ]
